Get Wazuh version from VERSION file
wazuh/wazuh-indexer pull request #122
Opened 2024-01-15 14:30 UTC by f-galland

### Description
This PR fixes getting the Wazuh Indexer version from the `VERSION` file within the repository when downloading Wazuh-specific configuration files and scripts.

### Issues Resolved
Resolves #117 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] GitHub issue/PR created in [OpenSearch documentation repo](https://github.com/opensearch-project/documentation-website) for the required public documentation changes (#[Issue/PR number])

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-01-15 19:18 UTC, f-galland commented
Packages are correctly generated with the right version string using the dockerized build and assemble environments:

![DeepinScreenshot_select-area_20240115161752](https://github.com/wazuh/wazuh-indexer/assets/99492720/e72240cb-619e-4dd1-a3e4-96e4db7db1ff)

2024-01-17 14:11 UTC, AlexRuiz7 requested changes
Let's try to split the new Docker environments to a new issue and PR.

2024-01-17 18:00 UTC, f-galland commented on scripts/provision.sh
> +apt-get update -y && apt-get upgrade -y && apt-get install -y curl wget build-essential &&
Fixed.

2024-01-19 11:08 UTC, AlexRuiz7 approved these changes
LGTM!

Workflow runs successfully! 

https://github.com/wazuh/wazuh-indexer/actions/runs/7582882220

2024-01-19 11:32 UTC, merged