Fix sysv files
wazuh/wazuh-indexer pull request #343
Opened 2024-08-02 12:37 UTC by f-galland

### Description
This PR fixes the `sysv` script under `/etc/init.d/wazuh-indexer`.

### Issues Resolved
solves #340 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-08-02 12:38 UTC, f-galland commented
After installing packages generated with the changes of this PR, the `service` commands operate as expected:

```shellsession
[root@alma9 ~]# curl -k -u admin:admin https://localhost:9200
{
  "name" : "node-1",
  "cluster_name" : "wazuh-cluster",
  "cluster_uuid" : "CQgc5AqSRzSg9HyWQd-u3g",
  "version" : {
    "number" : "7.10.2",
    "build_type" : "rpm",
    "build_hash" : "bf42358a96448dcf95cdde3cc82300267743a9e0",
    "build_date" : "2024-08-01T19:11:30.394888472Z",
    "build_snapshot" : false,
    "lucene_version" : "9.10.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
[root@alma9 ~]# service status wazuh-indexer
The service command supports only basic LSB actions (start, stop, restart, try-restart, reload, reload-or-restart, try-reload-or-restart, force-reload, status, condrestart). For other actions, please try to use systemctl.
[root@alma9 ~]# service wazuh-indexer status
● wazuh-indexer.service - wazuh-indexer
     Loaded: loaded (/usr/lib/systemd/system/wazuh-indexer.service; enabled; preset: disabled)
    Drop-In: /run/systemd/system/service.d
             └─zzz-lxc-service.conf
     Active: active (running) since Fri 2024-08-02 12:33:32 UTC; 34s ago
       Docs: https://documentation.wazuh.com
   Main PID: 6906 (java)
      Tasks: 123 (limit: 200975)
     Memory: 1.4G
        CPU: 33.254s
     CGroup: /system.slice/wazuh-indexer.service
             └─6906 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -XX:+ShowCodeDetailsInExceptionMessages -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.numDirectArenas=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.security.manager=allow -Djava.locale.providers=SPI,COMPAT -Xms1g -Xmx1g -XX:+UseG1GC -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -Djava.io.tmpdir=/var/log/wazuh-indexer/tmp -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/lib/wazuh-indexer -XX:ErrorFile=/var/log/wazuh-indexer/hs_err_pid%p.log "-Xlog:gc*,gc+age=trace,safepoint:file=/var/log/wazuh-indexer/gc.log:utctime,pid,tags:filecount=32,filesize=64m" -Djava.security.manager=allow -Djava.util.concurrent.ForkJoinPool.common.threadFactory=org.opensearch.secure_sm.SecuredForkJoinWorkerThreadFactory -Dclk.tck=100 -Djdk.attach.allowAttachSelf=true -Djava.security.policy=file:///etc/wazuh-indexer/opensearch-performance-analyzer/opensearch_security.policy --add-opens=jdk.attach/sun.tools.attach=ALL-UNNAMED -XX:MaxDirectMemorySize=536870912 -Dopensearch.path.home=/usr/share/wazuh-indexer -Dopensearch.path.conf=/etc/wazuh-indexer -Dopensearch.distribution.type=rpm -Dopensearch.bundled_jdk=true -cp "/usr/share/wazuh-indexer/lib/*" org.opensearch.bootstrap.OpenSearch -p /run/wazuh-indexer/wazuh-indexer.pid --quiet

Aug 02 12:33:25 alma9 systemd-entrypoint[6906]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.OpenSearch (file:/usr/share/wazuh-indexer/lib/opensearch-2.13.0.jar)
Aug 02 12:33:25 alma9 systemd-entrypoint[6906]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.OpenSearch
Aug 02 12:33:25 alma9 systemd-entrypoint[6906]: WARNING: System::setSecurityManager will be removed in a future release
Aug 02 12:33:26 alma9 systemd-entrypoint[6906]: Aug 02, 2024 12:33:26 PM sun.util.locale.provider.LocaleProviderAdapter <clinit>
Aug 02 12:33:26 alma9 systemd-entrypoint[6906]: WARNING: COMPAT locale provider will be removed in a future release
Aug 02 12:33:26 alma9 systemd-entrypoint[6906]: WARNING: A terminally deprecated method in java.lang.System has been called
Aug 02 12:33:26 alma9 systemd-entrypoint[6906]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.Security (file:/usr/share/wazuh-indexer/lib/opensearch-2.13.0.jar)
Aug 02 12:33:26 alma9 systemd-entrypoint[6906]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.Security
Aug 02 12:33:26 alma9 systemd-entrypoint[6906]: WARNING: System::setSecurityManager will be removed in a future release
Aug 02 12:33:32 alma9 systemd[1]: Started wazuh-indexer.
[root@alma9 ~]# service wazuh-indexer stop
Stopping wazuh-indexer (via systemctl):                    [  OK  ]
[root@alma9 ~]# service wazuh-indexer start
Starting wazuh-indexer (via systemctl):                    [  OK  ]
[root@alma9 ~]# ls -lsah /etc/init.d/wazuh-indexer 
4.0K -rwxr-xr-x 1 root root 3.6K Aug  2 12:27 /etc/init.d/wazuh-indexer
```

2024-08-05 10:02 UTC, AlexRuiz7 requested changes

2024-08-05 10:02 UTC, AlexRuiz7 commented on distribution/packages/src/rpm/wazuh-indexer.rpm.spec
> +%attr(0755, root, root) %{_sysconfdir}/init.d/%{name}
Should be 750

Compared with `wazuh-indexer.cicd.spec`
```
%attr(750, %{USER}, %{GROUP}) %{INSTALL_DIR}/bin/opensearch
```

2024-08-05 12:55 UTC, AlexRuiz7 approved these changes

2024-08-05 12:55 UTC, merged