Add event_generator tooling for 5.x indices
wazuh/wazuh-indexer pull request #526
Opened 2024-11-06 17:51 UTC by QU3B1M

### Description
[Describe what this change achieves]

### Related Issues
Resolves #518 

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-11-06 19:34 UTC, QU3B1M commented
All the event generator scripts were executed and validated

<details><summary><strong>Agent</strong> event generator</summary>

```bash
python agent/event-generator/event_generator.py 

How many events do you want to generate? 2
Do you want to inject the generated data into your indexer? (y/n) y
Enter the IP of your Indexer (default: '127.0.0.1'): 192.168.73.4
Enter the port of your Indexer (default: '9200'): 
Enter the index name (default: '.agents'): 
Username (default: 'admin'): 
Password (default: 'admin'): 
```

`generated data`
```JSON
curl -XGET https://192.168.73.4:9200/.agents/_search -u admin:admin --insecure

{
    "took": 2,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 2,
            "relation": "eq"
        },
        "max_score": 1.0,
        "hits": [
            {
                "_index": ".agents",
                "_id": "Z9reApMB5auTxkcxn7Xn",
                "_score": 1.0,
                "_source": {
                    "agent": {
                        "id": "agent26",
                        "name": "Agent18",
                        "type": "windows",
                        "version": "v2-stable",
                        "is_connected": true,
                        "last_login": "2024-11-01T06:50:53.090277Z",
                        "groups": [
                            "group22",
                            "group79"
                        ],
                        "key": "key134"
                    },
                    "host": {
                        "ip": "19.152.25.220",
                        "os": {
                            "full": "android 17.4"
                        }
                    }
                }
            },
            {
                "_index": ".agents",
                "_id": "aNreApMB5auTxkcxoLUF",
                "_score": 1.0,
                "_source": {
                    "agent": {
                        "id": "agent48",
                        "name": "Agent76",
                        "type": "windows",
                        "version": "v5-stable",
                        "is_connected": false,
                        "last_login": "2024-11-05T05:33:02.849669Z",
                        "groups": [
                            "group38",
                            "group5"
                        ],
                        "key": "key341"
                    },
                    "host": {
                        "ip": "184.76.160.44",
                        "os": {
                            "full": "android 34.58"
                        }
                    }
                }
            }
        ]
    }
}
```
</details>

<details><summary><strong>Commands</strong> event generator</summary>

```bash
python command/event-generator/event_generator.py 

How many events do you want to generate? 2
Do you want to inject the generated data into your indexer/command manager? (y/n) y
Enter the IP of your Indexer (default: '127.0.0.1'): 192.168.73.4
Enter the port of your Indexer (default: '9200'): 
Username (default: 'admin'): 
Password (default: 'admin'): 
```

`generated data`
```JSON
curl -XGET https://192.168.73.4:9200/.commands/_search -u admin:admin --insecure
{
    "took": 3,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 2,
            "relation": "eq"
        },
        "max_score": 1.0,
        "hits": [
            {
                "_index": ".commands",
                "_id": "a9rsApMB5auTxkcx27Wz",
                "_score": 1.0,
                "_source": {
                    "agent": {
                        "groups": [
                            "groups000"
                        ]
                    },
                    "command": {
                        "source": "Engine",
                        "user": "user81",
                        "target": {
                            "type": "group",
                            "id": "target3"
                        },
                        "action": {
                            "name": "apply_policy",
                            "args": [
                                "/path/to/executable/arg8"
                            ],
                            "version": "v5"
                        },
                        "timeout": 88,
                        "status": "PENDING",
                        "order_id": "atrsApMB5auTxkcx27Wz",
                        "request_id": "adrsApMB5auTxkcx27Wz"
                    }
                }
            },
            {
                "_index": ".commands",
                "_id": "btrsApMB5auTxkcx3LUA",
                "_score": 1.0,
                "_source": {
                    "agent": {
                        "groups": [
                            "groups000"
                        ]
                    },
                    "command": {
                        "source": "Content manager",
                        "user": "user94",
                        "target": {
                            "type": "group",
                            "id": "target1"
                        },
                        "action": {
                            "name": "change_group",
                            "args": [
                                "/path/to/executable/arg8"
                            ],
                            "version": "v4"
                        },
                        "timeout": 55,
                        "status": "PENDING",
                        "order_id": "bdrsApMB5auTxkcx3LUA",
                        "request_id": "bNrsApMB5auTxkcx3LUA"
                    }
                }
            }
        ]
    }
}

```
</details>

<details><summary><strong>FIM</strong> event generator</summary>

```bash
python states-fim/event-generator/event_generator.py 

How many events do you want to generate? 2
Do you want to inject the generated data into your indexer? (y/n) y
Enter the IP of your Indexer (default: '127.0.0.1'): 192.168.73.4
Enter the port of your Indexer (default: '9200'): 
Enter the index name (default: 'wazuh-states-fim'): 
Username (default: 'admin'): 
Password (default: 'admin'): 
```

`generated data`
```JSON
curl -XGET https://192.168.73.4:9200/wazuh-states-fim/_search -u admin:admin --insecure
{
    "took": 4,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 2,
            "relation": "eq"
        },
        "max_score": 1.0,
        "hits": [
            {
                "_index": "wazuh-states-fim",
                "_id": "b9ruApMB5auTxkcx_rWB",
                "_score": 1.0,
                "_source": {
                    "agent": {
                        "id": "agent70",
                        "groups": [
                            "group46",
                            "group95"
                        ]
                    },
                    "file": {
                        "attributes": "attr640",
                        "gid": "gid621",
                        "group": "group66",
                        "hash": {
                            "md5": "md5_379",
                            "sha1": "sha1_318",
                            "sha256": "sha256_780"
                        },
                        "inode": "inode680",
                        "mode": "mode199",
                        "mtime": "2024-11-01T09:51:40.024681Z",
                        "name": "file576",
                        "owner": "owner46",
                        "path": "/path/to/file488",
                        "size": 30845,
                        "target_path": "/path/to/target_file535",
 [...]

2024-11-07 11:37 UTC, AlexRuiz7 approved these changes

2024-11-08 09:35 UTC, AlexRuiz7 approved these changes

2024-11-08 19:15 UTC, QU3B1M commented
Events generators for new indices

<details><summary><strong>Inventory hardware</strong> event generator</summary>

```bash
 python states-inventory-hardware/event-generator/event_generator.py 

How many events do you want to generate? 2
Do you want to inject the generated data into your indexer? (y/n) y
Enter the IP of your Indexer (default: '127.0.0.1'): 192.168.73.4
Enter the port of your Indexer (default: '9200'): 
Enter the index name (default: 'wazuh-states-inventory-hardware'): 
Username (default: 'admin'): 
Password (default: 'admin'): 
```

`generated data`
```JSON
curl -XGET https://192.168.73.4:9200/wazuh-states-inventory-hardware/_search -u admin:admin --insecure

{
    "took": 31,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 2,
            "relation": "eq"
        },
        "max_score": 1.0,
        "hits": [
            {
                "_index": "wazuh-states-inventory-hardware",
                "_id": "z10tDZMB4hG3b5a-Fy1r",
                "_score": 1.0,
                "_source": {
                    "@timestamp": "2024-11-08T16:07:42.481732Z",
                    "agent": {
                        "id": "agent79",
                        "groups": [
                            "group45",
                            "group91"
                        ]
                    },
                    "host": {
                        "cpu": {
                            "cores": 6,
                            "name": "cpu_20",
                            "speed": 3176
                        },
                        "memory": {
                            "free": 10989,
                            "total": 8955,
                            "used": {
                                "percentage": 22
                            }
                        }
                    },
                    "observer": {
                        "serial_number": "3635324586"
                    }
                }
            },
            {
                "_index": "wazuh-states-inventory-hardware",
                "_id": "0F0tDZMB4hG3b5a-Fy3C",
                "_score": 1.0,
                "_source": {
                    "@timestamp": "2024-11-08T16:07:42.481860Z",
                    "agent": {
                        "id": "agent58",
                        "groups": [
                            "group16",
                            "group44"
                        ]
                    },
                    "host": {
                        "cpu": {
                            "cores": 16,
                            "name": "cpu_324",
                            "speed": 3068
                        },
                        "memory": {
                            "free": 15121,
                            "total": 19200,
                            "used": {
                                "percentage": 90
                            }
                        }
                    },
                    "observer": {
                        "serial_number": "1850060648"
                    }
                }
            }
        ]
    }
}
```
</details>

<details><summary><strong>Inventory hotfixes</strong> event generator</summary>

```bash
python states-inventory-hotfixes/event-generator/event_generator.py

How many events do you want to generate? 2
Do you want to inject the generated data into your indexer? (y/n) y
Enter the IP of your Indexer (default: '127.0.0.1'): 192.168.73.4
Enter the port of your Indexer (default: '9200'): 
Enter the index name (default: 'wazuh-states-inventory-hotfixes'): 
Username (default: 'admin'): 
Password (default: 'admin'): 
```

`generated data`
```JSON
curl -XGET https://192.168.73.4:9200/wazuh-states-inventory-hotfixes/_search -u admin:admin --insecure

{
    "took": 3,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 2,
            "relation": "eq"
        },
        "max_score": 1.0,
        "hits": [
            {
                "_index": "wazuh-states-inventory-hotfixes",
                "_id": "0V0wDZMB4hG3b5a-LC0r",
                "_score": 1.0,
                "_source": {
                    "@timestamp": "2024-11-08T16:11:11.186753Z",
                    "agent": {
                        "id": "agent2",
                        "groups": [
                            "group15",
                            "group6"
                        ]
                    },
                    "package": {
                        "hotfix": {
                            "name": "hotfix_174"
                        }
                    }
                }
            },
            {
                "_index": "wazuh-states-inventory-hotfixes",
                "_id": "0l0wDZMB4hG3b5a-LC2D",
                "_score": 1.0,
                "_source": {
                    "@timestamp": "2024-11-08T16:11:11.186947Z",
                    "agent": {
                        "id": "agent7",
                        "groups": [
                            "group27",
                            "group35"
                        ]
                    },
                    "package": {
                        "hotfix": {
                            "name": "hotfix_924"
                        }
                    }
                }
            }
        ]
    }
}
```
</details>

<details><summary><strong>Inventory networks</strong> event generator</summary>

```bash
python states-inventory-networks/event-generator/event_generator.py

How many events do you want to generate? 2
Do you want to inject the generated data into your indexer? (y/n) y
Enter the IP of your Indexer (default: '127.0.0.1'): 192.168.73.4
Enter the port of your Indexer (default: '9200'): 
Enter the index name (default: 'wazuh-states-inventory-networks'): 
Username (default: 'admin'): 
Password (default: 'admin'): 
```

`generated data`
```JSON
curl -XGET https://192.168.73.4:9200/wazuh-states-inventory-networks/_search -u admin:admin --insecure

{
    "took": 2,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 2,
            "relation": "eq"
        },
        "max_score": 1.0,
        "hits": [
            {
                "_index": "wazuh-states-inventory-networks",
                "_id": "010yDZMB4hG3b5a-ky3t",
                "_score": 1.0,
                "_source": {
                    "@timestamp": "2024-11-08T16:13:47.624659Z",
                    "agent": {
                        "id": "agent48",
                        "groups": [
                            "group92",
                            "group69"
                        ]
                    },
                    "destination": {
                        "ip": "25.173.249.92",
                        "port": 34683
                    },
                    "device": {
                        "id": "device625"
                    },
                    "file": {
                        "inode": "inode66"
                    },
                    "host": {
                        "ip": "88.144.215.48",
                        "mac": "a3:9b:59:0a:fa:21",
                        "network": {
                            "egress": {
                                "bytes": 383414,
                                "packets": 4311
                            },
                            "ingress": {
                                "bytes": 587868,
                                "packets": 9998
                            }
                        }
                    },
                    "network": {
                        "protocol": "UDP",
        [...]

2024-11-11 17:54 UTC, AlexRuiz7 commented
Pending changes on #525 and #539.

2024-11-11 17:56 UTC, AlexRuiz7 requested changes
Pending changes on https://github.com/wazuh/wazuh-indexer/issues/525 and https://github.com/wazuh/wazuh-indexer/issues/539.

2024-11-13 20:05 UTC, QU3B1M commented
Events generators updated with the index templates modifications

<details><summary><strong>agents</strong> event generated</summary>

It returns an error when creating the doc using all the fields (`event_generator.py` pushed on this PR)
```bash
ERROR:root:{"error":{"root_cause":[{"type":"strict_dynamic_mapping_exception","reason":"mapping set to strict, dynamic introduction of [host] within [_doc] is not allowed"}],"type":"strict_dynamic_mapping_exception","reason":"mapping set to strict, dynamic introduction of [host] within [_doc] is not allowed"},"status":400}
```

Also tested with a minimal version of the index, and also returns an error
```bash
ERROR:root:{"error":{"root_cause":[{"type":"strict_dynamic_mapping_exception","reason":"mapping set to strict, dynamic introduction of [is_connected] within [agent] is not allowed"}],"type":"strict_dynamic_mapping_exception","reason":"mapping set to strict, dynamic introduction of [is_connected] within [agent] is not allowed"},"status":400}
```
<details><summary><code>event_generator.py</code> used for this case</summary>

```python
#!/bin/python3

import datetime
import json
import logging
import random
import requests
import urllib3

# Constants and Configuration
LOG_FILE = 'generate_data.log'
GENERATED_DATA_FILE = 'generatedData.json'
DATE_FORMAT = "%Y-%m-%dT%H:%M:%S.%fZ"
# Default values
INDEX_NAME = ".agents"
USERNAME = "admin"
PASSWORD = "admin"
IP = "127.0.0.1"
PORT = "9200"

# Configure logging
logging.basicConfig(filename=LOG_FILE, level=logging.INFO)

# Suppress warnings
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


def generate_random_date():
    start_date = datetime.datetime.now()
    end_date = start_date - datetime.timedelta(days=10)
    random_date = start_date + (end_date - start_date) * random.random()
    return random_date.strftime(DATE_FORMAT)


def generate_random_agent():
    agent = {
        'id': f'agent{random.randint(0, 9999)}',
        'name': f'Agent{random.randint(0, 9999)}',
        'type': random.choice(['endpoint', 'filebeat', 'windows', 'linux', 'macos']),
        'version': f'v{random.randint(0, 9)}.0.0',
        'groups': [f'group{random.randint(0, 99)}', f'group{random.randint(0, 99)}'],
        'key': f'key{random.randint(0, 9999)}',
        'last_login': generate_random_date(),
        'is_connected': bool(random.choice([True, False]))
    }
    return agent


def generate_random_host():
    host = {
        'ip': [f'{random.randint(1, 255)}.{random.randint(0, 255)}.{random.randint(0, 255)}.{random.randint(0, 255)}'],
        'os': {
            'full': f'{random.choice(["Windows 10", "Ubuntu 20.04", "Mac OS Mojave"])}'
        }
    }
    return host


def generate_random_data(number):
    data = []
    for _ in range(number):
        event_data = {
            'agent': generate_random_agent(),
            'host': generate_random_host(),
        }
        data.append(event_data)
    return data


def inject_events(ip, port, index, username, password, data):
    url = f'https://{ip}:{port}/{index}/_doc'
    session = requests.Session()
    session.auth = (username, password)
    session.verify = False
    headers = {'Content-Type': 'application/json'}

    try:
        for event_data in data:
            response = session.post(url, json=event_data, headers=headers)
            if response.status_code != 201:
                logging.error(f'Error: {response.status_code}')
                logging.error(response.text)
                break
        logging.info('Data injection completed successfully.')
    except Exception as e:
        logging.error(f'Error: {str(e)}')


def main():
    try:
        number = int(input("How many events do you want to generate? "))
    except ValueError:
        logging.error("Invalid input. Please enter a valid number.")
        return

    logging.info(f"Generating {number} events...")
    data = generate_random_data(number)

    with open(GENERATED_DATA_FILE, 'a') as outfile:
        for event_data in data:
            json.dump(event_data, outfile)
            outfile.write('\n')

    logging.info('Data generation completed.')

    inject = input("Do you want to inject the generated data into your indexer? (y/n) ").strip().lower()
    if inject == 'y':
        ip = input(f"Enter the IP of your Indexer (default: '{IP}'): ") or IP
        port = input(f"Enter the port of your Indexer (default: '{PORT}'): ") or PORT
        index = input(f"Enter the index name (default: '{INDEX_NAME}'): ") or INDEX_NAME
        username = input(f"Username (default: '{USERNAME}'): ") or USERNAME
        password = input(f"Password (default: '{PASSWORD}'): ") or PASSWORD
        inject_events(ip, port, index, username, password, data)


if __name__ == "__main__":
    main()
```

</details>

<details><summary><strong>FIM</strong> event generated</summary>

```JSON
{
    "took": 2,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 1,
            "relation": "eq"
        },
        "max_score": 1.0,
        "hits": [
            {
                "_index": "wazuh-states-fim",
                "_id": "r4sTJ5MB9HDzDXmhhwSZ",
                "_score": 1.0,
                "_source": {
                    "agent": {
                        "id": "agent75",
                        "groups": [
                            "group60",
                            "group86"
                        ],
                        "host": {
                            "architecture": "arm64",
                            "boot": {
                                "id": "bootid4766"
                            },
                            "cpu": {
                                "usage": 13.046286085527425
                            },
                            "disk": {
                                "read": {
                                    "bytes": 306709
                                },
                                "write": {
                                    "bytes": 772570
                                }
                            },
                            "domain": "domain757",
                            "geo": {
                                "city_name": "CityName",
                                "continent_code": "NA",
                                "continent_name": "North America",
                                "country_iso_code": "US",
                                "country_name": "United States",
                                "location": {
                                    "lat": 87.054545,
                                    "lon": -178.442628
                                },
                                "name": "hostname67",
                                "postal_code": "35570",
                                "region_iso_code": "US-CA",
                                "region_name": "California",
                                "timezone": "America/Los_Angeles"
                            },
                            "hostname": "host140",
                            "id": "id95",
                            "ip": "215.114.78.214",
                            "mac": "37:8c:28:bc:59:ce",
                            "name": "host213",
                            "network": {
                                "egress": {
                                    "bytes": 798164,
                                    "packets": 8133
                                },
                                "ingress": {
                                    "bytes": 719944,
                                    "packets": 4302
                                }
                            },
                            "os": {
                                "family": "ios",
                                "full": "android 95.77",
                                "kernel": "6.7.1",
 [...]

2024-11-15 12:11 UTC, AlexRuiz7 approved these changes

2024-11-15 12:14 UTC, AlexRuiz7 commented
Documents are indexed correctly.
```
health status index                            uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   wazuh-states-fim                 bC6NjlZrTeemBD5pWz9vKA   1   0        151            0    387.5kb        387.5kb
green  open   wazuh-states-inventory-ports     DVxo3v36SFyAar6BgRKOhw   1   0        150            0    323.4kb        323.4kb
green  open   wazuh-states-inventory-hotfixes  4YGpI8BjSa2PjorrHFyf_g   1   0        150            0    282.4kb        282.4kb
green  open   wazuh-states-inventory-system    bApxb5xVTMedCH6GHpkWDg   1   0        150            0    319.3kb        319.3kb
green  open   wazuh-states-inventory-networks  k3Ahkh0LR2GC0ESgmUjhWg   1   0        150            0    370.7kb        370.7kb
green  open   wazuh-states-inventory-packages  L-4gRxKrRkKZIa6C64KmMg   1   0        300            0    717.2kb        717.2kb
green  open   .opendistro_security             Oq-1K6y1S7O8uD0s0oc62Q   1   1         10            0    156.9kb         78.4kb
green  open   wazuh-states-inventory-hardware  eNap250NTmaTngy27h-efA   1   0        150            0    364.3kb        364.3kb
green  open   .plugins-ml-config               JGzz0FZtRZeRHjs8z-3u-g   1   1          1            0      7.8kb          3.9kb
green  open   .opensearch-observability        kHzYio2FSGSX5KzHBT7Xvw   1   1          0            0       416b           208b
green  open   wazuh-states-vulnerabilities     alCipp5MQWat_OzaXHDmcg   1   0        150            0    377.9kb        377.9kb
green  open   wazuh-alerts-5.x-0001            lFktuzz6QcO8D0UprReGhQ   1   0          0            0       208b           208b
green  open   wazuh-states-inventory-processes 2FGzHhSKQrqoIVqYsGmASw   1   0        150            0    340.8kb        340.8kb
```

2024-11-15 12:25 UTC, f-galland submitted a review, later dismissed

2024-11-15 12:46 UTC, AlexRuiz7 requested changes
Needs to be ported to `master`.

2024-11-15 15:56 UTC, f-galland commented
Closing this in favor of #553

2024-11-15 15:56 UTC, closed without merging