Add initial ecs Dockerfile
wazuh/wazuh-indexer pull request #586
Opened 2024-12-10 13:25 UTC by QU3B1M

### Description
[Describe what this change achieves]

### Related Issues
Resolves #540 

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-12-23 15:51 UTC, AlexRuiz7 requested changes

2024-12-23 15:51 UTC, AlexRuiz7 commented on .github/workflows/generate-ecs-mappings.yml
> +      - 'ecs/**'
Filter to run on modifications to json and yaml files.

2024-12-23 15:51 UTC, AlexRuiz7 commented on .github/workflows/generate-ecs-mappings.yml
> +    runs-on: ubuntu-latest
Prefer using fixed version for runners, for example, ubuntu-24.04.

2024-12-23 15:51 UTC, AlexRuiz7 commented on docker/ecs/images/generator.sh
> +  )' "$in_file" > "$out_file"
Needs update with master

2024-12-23 15:51 UTC, AlexRuiz7 commented on docker/ecs/images/generator.sh
This file is a duplication of `ecs/generate.sh`, requiring us to maintain both. It would be great if these were unified.

2025-01-06 14:36 UTC, f-galland commented
I tested this in a personal fork:
* https://github.com/f-galland/wazuh-indexer/tree/ci/540-ecs-index-automatic-generation

The Workflow was failing due to a non-zero exit code in the [generate-pr-to-plugins.sh](https://github.com/f-galland/wazuh-indexer/blob/ci/540-ecs-index-automatic-generation/ecs/scripts/generate-pr-to-plugins.sh) script triggering `set -e` to exit altogether.

Fixing that got the PR generation working:
* https://github.com/f-galland/wazuh-indexer-plugins/pull/1

2025-01-06 15:32 UTC, f-galland commented
The latest changes make updates to mappings trigger updates in PR description work.

2025-01-07 12:44 UTC, AlexRuiz7 requested changes

2025-01-07 12:44 UTC, AlexRuiz7 commented on .github/workflows/generate-ecs-mappings.yml
> +      - name: Generate PR to wazuh-indxer-plugins
typo here

2025-01-07 12:44 UTC, AlexRuiz7 commented on .github/workflows/generate-ecs-mappings.yml
> +          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
Secret needs to be set at repository level.

2025-01-07 12:44 UTC, AlexRuiz7 commented on ecs/generator/images/Dockerfile
> +    git clone https://github.com/elastic/ecs.git -b v8.11.0 --depth 1 && \
ECS version could be extracted as a variable.

2025-01-07 12:44 UTC, AlexRuiz7 commented on ecs/README.md
> +For our use case, the most important files are under `mappings/v8.11.0/generated/elasticsearch/legacy/`:
I'd keep it generic as it was before. This path is not correct if a different version is specified to the mapping generator tool.

2025-01-07 12:44 UTC, AlexRuiz7 commented on ecs/generator/mapping-generator.yml
> +      - ECS_MODULE=${ECS_MODULE:-default_module}
`default_module` is not referenced anywhere else.

2025-01-07 12:44 UTC, AlexRuiz7 commented on ecs/scripts/generate-pr-to-plugins.sh
> +MAPPINGS_SUBPATH="mappings/v8.11.0/generated/elasticsearch/legacy/template.json"
Hardcoded version

2025-01-07 12:44 UTC, AlexRuiz7 commented on ecs/scripts/generate-pr-to-plugins.sh
> +fetch_and_extract_modules() {
`detect_modified_modules()` would be a more straightforward name for this function.

2025-01-07 12:44 UTC, AlexRuiz7 commented on ecs/scripts/generate-pr-to-plugins.sh
Add comments to each function.

Can this script be run locally? If so, which are its dependencies, and how could it be executed? That information should be present in the README.

2025-01-07 12:44 UTC, AlexRuiz7 commented on ecs/README.md
> +- [Docker Desktop](https://docs.docker.com/desktop/setup/install/linux/)
Is it Docker Desktop actually a requirement? I think `docker compose` is, which can be installed without Docker Desktop.

Prefer docker and docker compose plugin instead, as it's a slimmer installation and less problematic (we'be had problems with Docker Desktop in the past).

2025-01-07 16:07 UTC, QU3B1M commented on ecs/README.md
> +- [Docker Desktop](https://docs.docker.com/desktop/setup/install/linux/)
Noted! Updated, now the dependency is just Docker Compose

2025-01-07 16:08 UTC, QU3B1M commented on ecs/scripts/generate-pr-to-plugins.sh
> +MAPPINGS_SUBPATH="mappings/v8.11.0/generated/elasticsearch/legacy/template.json"
Fixed in commit 67a71bdf9893ffc04da66130e9134440ef3a7229

2025-01-07 16:08 UTC, QU3B1M commented on ecs/scripts/generate-pr-to-plugins.sh
> +fetch_and_extract_modules() {
Thanks! Applied in commit 67a71bdf9893ffc04da66130e9134440ef3a7229

2025-01-07 16:25 UTC, QU3B1M commented on .github/workflows/generate-ecs-mappings.yml
> +          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
Yes, this Action secret should be configured at repository

2025-01-07 16:35 UTC, AlexRuiz7 approved these changes

2025-01-08 11:38 UTC, AlexRuiz7 requested changes

2025-01-08 11:38 UTC, AlexRuiz7 commented on .github/workflows/generate-ecs-mappings.yml
> +        if: github.repository == 'wazuh/wazuh-indexer'
This condition should be set at job's level

```yml
jobs:
  run-ecs-generator:
    if: github.repository == 'wazuh/wazuh-indexer'
    runs-on: ubuntu-24.04
```

2025-01-08 11:48 UTC, QU3B1M commented on .github/workflows/generate-ecs-mappings.yml
> +        if: github.repository == 'wazuh/wazuh-indexer'
Fixed on https://github.com/wazuh/wazuh-indexer/pull/586/commits/6fbfe0dfc6dc68b397de945fc803221863b41ec8

2025-01-08 11:48 UTC, AlexRuiz7 approved these changes

2025-01-23 16:09 UTC, AlexRuiz7 approved these changes

2025-01-23 16:09 UTC, merged